Use error() more often

diff --git a/developer/deken b/developer/deken
--- a/developer/deken
+++ b/developer/deken
@@ -8,10 +8,14 @@
 
 export DEKEN_VERSION="0.1"
 
+error() {
+    echo "$@" 1>&2
+}
+
 if [ $(id -u) -eq 0 ] && [ "$DEKEN_ROOT" = "" ]; then
-    echo "WARNING: You're currently running as root; probably by accident."
-    echo "Press control-C to abort or Enter to continue as root."
-    echo "Set DEKEN_ROOT to disable this warning."
+    error "WARNING: You're currently running as root; probably by accident."
+    error "Press control-C to abort or Enter to continue as root."
+    error "Set DEKEN_ROOT to disable this warning."
     read _
 fi
 
@@ -45,10 +49,6 @@ DEKEN_BASE_URL="https://raw.githubusercontent.com/pure-data/deken/master/develop
 if $cygwin; then
     export DEKEN_HOME=$(cygpath -w "$DEKEN_HOME")
 fi
-
-error() {
-    echo "$@" 1>&2
-}
 
 bail_install() {
     error "Self-installation of Deken failed."
